apiVersion: v1
kind: Namespace
metadata:
  name: #{Release.EnvironmentName}#
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springbootdemo
  namespace: #{Release.EnvironmentName}#
spec:
  replicas: #{Release.SpringBootDemo.Replicas}#
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
      - image: drinkbirdrestaurant.azurecr.io/springbootdemo:#{Release.Artifacts.SpringBootDemo.BuildNumber}#
        name: springbootdemo
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: azurecr
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
  namespace: #{Release.EnvironmentName}#
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootdemo
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootdemo
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: springbootdemo.4373ebc07f65467895dd.northeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: springbootdemo
          servicePort: 80
        path: /