apiVersion: v1
kind: Namespace
metadata:
  name: #{Release.EnvironmentName}#
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reservations-api
  namespace: #{Release.EnvironmentName}#
spec:
  template:
    metadata:
      labels:
        app: reservations-api
    spec:
      imagePullSecrets:
      - name: azurecr
      containers:
      - image: drinkbirdrestaurant.azurecr.io/reservations-api:#{Release.Artifacts.reservations-api.BuildNumber}#
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: reservations-api-secret
              key: mongodburi
        name: reservations-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-api
  namespace: #{Release.EnvironmentName}#
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: reservations-api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reservations-api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: reservations-api.4373ebc07f65467895dd.northeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: reservations-api
          servicePort: 80
        path: /